// Autogenerated from Pigeon (v1.0.14), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class InitializeRequest;
@class SetDepartmentRequest;
@class StartChatRequest;
@class SetVisitorInfoRequest;
@class VisitorTagsRequest;
@class VisitorNoteRequest;

@interface InitializeRequest : NSObject
@property(nonatomic, copy, nullable) NSString * accountKey;
@property(nonatomic, copy, nullable) NSString * appId;
@property(nonatomic, copy, nullable) NSString * deviceToken;
@end

@interface SetDepartmentRequest : NSObject
@property(nonatomic, copy, nullable) NSString * department;
@end

@interface StartChatRequest : NSObject
@property(nonatomic, strong, nullable) NSNumber * isPreChatFormEnabled;
@property(nonatomic, strong, nullable) NSNumber * isOfflineFormEnabled;
@property(nonatomic, strong, nullable) NSNumber * isAgentAvailabilityEnabled;
@property(nonatomic, strong, nullable) NSNumber * isChatTranscriptPromptEnabled;
@property(nonatomic, copy, nullable) NSString * messagingName;
@property(nonatomic, copy, nullable) NSString * iosBackButtonTitle;
@property(nonatomic, strong, nullable) NSNumber * iosNavigationBarColor;
@property(nonatomic, strong, nullable) NSNumber * iosNavigationTitleColor;
@end

@interface SetVisitorInfoRequest : NSObject
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, copy, nullable) NSString * email;
@property(nonatomic, copy, nullable) NSString * phoneNumber;
@end

@interface VisitorTagsRequest : NSObject
@property(nonatomic, strong, nullable) NSArray<NSString *> * tags;
@end

@interface VisitorNoteRequest : NSObject
@property(nonatomic, copy, nullable) NSString * note;
@end

/// The codec used by ChatApi.
NSObject<FlutterMessageCodec> *ChatApiGetCodec(void);

@protocol ChatApi
- (void)initializeRequest:(InitializeRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setDepartmentRequest:(SetDepartmentRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)startChatRequest:(StartChatRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ChatApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ChatApi> *_Nullable api);

/// The codec used by ProfileApi.
NSObject<FlutterMessageCodec> *ProfileApiGetCodec(void);

@protocol ProfileApi
- (void)setVisitorInfoRequest:(SetVisitorInfoRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)addVisitorTagsRequest:(VisitorTagsRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)removeVisitorTagsRequest:(VisitorTagsRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setVisitorNoteRequest:(VisitorNoteRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)appendVisitorNoteRequest:(VisitorNoteRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)clearVisitorNotesWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ProfileApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ProfileApi> *_Nullable api);

NS_ASSUME_NONNULL_END
