name: zendesk_null_safety
description: Flutter interface for Zendesk Mobile SDK
version: 1.0.0
homepage: https://github.com/chearuno/zendesk-flutter

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^1.0.14
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.codeheadlabs.zendesk
        pluginClass: ZendeskPlugin
      ios:
        pluginClass: ZendeskPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"
